# Use an official Node.js runtime as a parent image
FROM node:alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN timeout 300 npm install

# Copy the local source files to the container
COPY . .

# Build the React app
RUN timeout 300 npm run build

# Expose the port that the app will run on (adjust as needed)
EXPOSE 8081

# Specify the command to run on container start
CMD ["npm", "start"]

# Add metadata to the image (replace "your-image-name" with the desired name)
LABEL name="mf-app1"
